on:
  push:
    branches:
      - branch1





jobs:
  build:
    run-on: ubuntu-latest


    steps:
      - name: 'Testing Github action'
        run: pwd

      - name: 'Testing printing'
        run: echo Mohamed
