on:
  push:
    branches:
      - branch1





jobs:
  build:
    runs-on: ubuntu-latest


    steps:
   
      - name: 'After'
        run: ls

      - uses: actions/checkout@v3

      - name: 'Before'
        run: ls
  
